domain_path: C:\Users\beful\Downloads\WSU-SPRING-26\EE234\Proj1\blackboard-platform\export\blackboard-platform\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\programs\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
